---
- name: Set up docker repository
  ansible.builtin.get_url:
    url: "{{ docker_release_redhat_repository }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  register: docker_repo_download
  retries: 5
  delay: 5
  until: docker_repo_download is succeeded

